name: Integration Continue
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://hhurchand/bdeb_mlflow_boston:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo hello > ${{ github.workspace }}/artifact/world.txt
          pip install -r requirements.txt
          pip install mlflow
          mlflow run . -e train.py
          mlflow ui

